### PR TITLE
Translation update German

### PR DESCRIPTION
**Pull request by OliveGerste**

### CODE REVIEW

**Comment by AlixH** [comment]
@OliveGerste , I have just translated badge to Ladekarte(n), seems right to you ?

**Comment by OliveGerste** [comment]
> @OliveGerste , I have just translated badge to Ladekarte(n), seems right to you ?

Yes I would say Ladekarte(n) is better, but we should also change this in the Front End then.

**Comment by AlixH** [comment]
> > @OliveGerste , I have just translated badge to Ladekarte(n), seems right to you ?
> 
> Yes I would say Ladekarte(n) is better, but we should also change this in the Front End then.

You mean in the dashobard ?

**Comment by OliveGerste** [comment]
> > > > @OliveGerste , I have just translated badge to Ladekarte(n), seems right to you ?
> > > 
> > > 
> > > Yes I would say Ladekarte(n) is better, but we should also change this in the Front End then.
> > 
> > 
> > You mean in the dashobard ?
> 
> @OliveGerste , I don't know about the articles (den, des, etc) so it would be easier if you could do it.

Yes of course. It makes more sense that I do it.

**Comment by AlixH** [comment]
> > > > > @OliveGerste , I have just translated badge to Ladekarte(n), seems right to you ?
> > > > 
> > > > 
> > > > Yes I would say Ladekarte(n) is better, but we should also change this in the Front End then.
> > > 
> > > 
> > > You mean in the dashobard ?
> > 
> > 
> > @OliveGerste , I don't know about the articles (den, des, etc) so it would be easier if you could do it.
> 
> Yes of course. It makes more sense that I do it.

Maybe double check the mobile occurences of Ledekarte, because I have only replace badge with it

**Pull request merged**
