### PR TITLE
Select car

### PR DESCRIPTION
**Pull request by AlixH**
- [x] Added car selection for start transaction
- [x] Aligned cars style with other lists

### CODE REVIEW

**Comment by LucasBrazi06** [comment]
@AlixH Do not forget to attach your PR to an issue ;-)
I just did it

**Review by LucasBrazi06 — APPROVED** [review]
Fixed initial car loading
Display in car list the Default car
Added icons above selected user / car
UserID and CarID not passed to the HTTP call

**Comment by AlixH** [comment]
> Fixed initial car loading
> Display in car list the Default car
> Added icons above selected user / car
> UserID and CarID not passed to the HTTP call
> 

@LucasBrazi06 , is it to do ? Some have past tense so I am mot sure
Concerning the start, I will do a final PR after the tag selection to send the infos, here I am just concentrating on the selection

**Comment by LucasBrazi06** [comment]
> @LucasBrazi06 , is it to do ? Some have past tense so I am mot sure

No, it's done :-).
It's just to inform you and if you agree with the changes.
Okay for the HTTP call.
I also removed the Available connector icon as this is the only use case where we display the selection.

**Pull request merged**
