### PR TITLE
Tags list

### PR DESCRIPTION
**Pull request by AlixH**
- [x] Tags list, searchable with count, tag status, description, id and user
- [x]  Fetch user image from UserComponent

### CODE REVIEW

**Review by LucasBrazi06 — APPROVED** [review]
Check my commits.
We can have a meeting to more explanation.
You need to improve your Flex Box skills:
https://css-tricks.com/snippets/css/a-guide-to-flexbox/
Try to keep the CSS keys naming meaningful and don't keep the ones not used
Keep consistent naming in class UsersList -> Users and TagsList -> Tags

**Comment by AlixH** [comment]
I understand your changes. However, I think some changes broke the ellipsis truncation of : users names, tags description, tags users name and tags id

Screenshot 2021-03-27 at 11 09 38

Screenshot 2021-03-27 at 11 13 21

Screenshot 2021-03-27 at 11 17 28

**Comment by LucasBrazi06** [comment]
> I understand your changes. However, I think some changes broke the ellipsis truncation of : users names, tags description, tags users name and tags id

Yes indeed!
I just fixed this.
Thanks for reporting.
Let me know if I broke something else.

**Comment by AlixH** [comment]
The tag's user's name still goes off the screen. 

Screenshot 2021-03-27 at 14 07 38

This is because the ellipsizeMode property of the Text component needs a size to know when to truncate
Having two flex items that both need to be truncated is a behaviour I only managed to have by doing the following: 

- Give a width to the userContainer


Screenshot 2021-03-27 at 14 25 01


- Add flexDirection:row and justifyContent:flex-end so that the user name is aligned to the right of the screen when there is still space

Screenshot 2021-03-27 at 14 26 27

I have the exact same behavior on Cars inside the header of CarComponent with the car name on the right on the license plate on the right

**Comment by LucasBrazi06** [comment]
Yes I know, that's okay, I just forgot this one ;)

**Comment by LucasBrazi06** [comment]
> The tag's user's name still goes off the screen

Just pushed my changes, let me know.
Double check with the car styling.
Thanks!

**Pull request merged**
