### PR TITLE
Refactored connector details

### PR DESCRIPTION
**Pull request by AlixH**
Major refactor of the connector details screen
- [x] Style improvements
- [x] User-friendly error messages
- [x] Added connector infos
- [x] Locked orientation to portrait for the charge point (not for the chart)
- [x] Improved conditional Start disabling
- [x] Improved conditions for disabled and openable modals for user/tag/car selection
- [x] Only display active badges in the modal
- [x] Refactored stop transaction dialog

Screenshot 2021-09-06 at 17 55 34
Screenshot 2021-09-06 at 17 55 42
Screenshot 2021-09-06 at 17 55 56
Screenshot 2021-09-06 at 18 14 50
Screenshot 2021-09-06 at 18 14 26

### CODE REVIEW

**Comment by LucasBrazi06** [comment]
@AlixH  Conflicts to resolve ;-)

**Comment by AlixH** [comment]
> @AlixH Conflicts to resolve ;-)

Yep, I'm on it

**Comment by AlixH** [comment]
I'll make tests with my car tomorrow

**Comment by LucasBrazi06** [comment]
I had moved your draft PR in Dev Cross Review.
No Draft PR in To Be Reviewed pipeline.
No that it is mergeable, I moved it to To Be Reviewed.

**Comment by AlixH** [comment]
> I had moved your draft PR in Dev Cross Review.
> No Draft PR in To Be Reviewed pipeline.
> No that it is mergeable, I moved it to To Be Reviewed.

Got it ! thanks

**Comment by LucasBrazi06** [comment]
Great redesign ! :-)
I'll test it.

**Comment by LucasBrazi06** [comment]
Not centered:


Missing active:


Add a toggle button Show/Hide Charging Session Settings (default is hidden if nothing is missing)
When displayed, always enable all.
Remove also white borders in Car


Set rounded borders of the images (1)
Move the User below the name of the car and reduce the size of the image to display more cars in the list.

**Comment by AlixH** [comment]
The idea of the switch button is to reset the default settings easily. I've hidden the settings because it confuses people when talking about it (Hanno, Gerald). Also we can add more infos in the connector section.
I think it's good to disable the car and badge when only one is available
Also I think it's good the keep sections labels/titles, the user instantaneously understands what are the settings, also when there is an error/placeholder message displayed
I've tried the rounded border in cars but it's weird ad the lines cut perpendicullary

**Comment by AlixH** [comment]
> Not centered:
> 
> 
> Missing active:
> 
> 
> Add a toggle button Show/Hide Charging Session Settings (default is hidden if nothing is missing)
> When displayed, always enable all.
> Remove also white borders in Car
> 
> 
> Set rounded borders of the images (1)
> Move the User below the name of the car and reduce the size of the image to display more cars in the list.
> 

The idea of the switch button is to reset the default settings easily. I've hidden the settings because it confuses people when talking about it (Hanno, Gerald). Also we can add more infos in the connector section.
I think it's good to disable the car and badge when only one is available
Also I think it's good the keep sections labels/titles, the user instantaneously understands what are the settings, also when there is an error/placeholder message displayed
I've tried the rounded border in cars but it's weird ad the lines cut perpendicullary

**Comment by LucasBrazi06** [comment]
> The idea of the switch button is to reset the default settings easily. I've hidden the settings because it confuses people when talking about it (Hanno, Gerald). Also we can add more infos in the connector section. and when something is missing, a red asterisk invites the user to check the settings (I can also make the text red)

If you read me correctly, the details is hidden when everything but displayed in the same screen.
You show it automatically only when something is missing.
No need for the user to click to check it.
And this is what Hanno/Gerald wanted.

> I think it's good to disable the car and badge when only one is available
No, as you have to explain why it is disabled and the others not, so keep the same behavior for all.

> Also I think it's good the keep sections labels/titles, the user instantaneously understands what are the settings, also when there is an error/placeholder message displayed
No, the user looks at the images not the text.
The icons (user, card, car) are self-explanatory, text only adds complexity to your eyes ;-).

> I've tried the rounded border in cars but it's weird ad the lines cut perpendicularly
I don't see what you mean (screenshot?)

**Comment by AlixH** [comment]
> > The idea of the switch button is to reset the default settings easily. I've hidden the settings because it confuses people when talking about it (Hanno, Gerald). Also we can add more infos in the connector section. and when something is missing, a red asterisk invites the user to check the settings (I can also make the text red)
> 
> If you read me correctly, the details is hidden when everything but displayed in the same screen.
> You show it automatically only when something is missing.
> No need for the user to click to check it.
> And this is what Hanno/Gerald wanted.
I could focus on the settings tab when there is an error also.
But ok ! 
But I still think that the toggle for default settings is useful. Reset the settings to the one of the current user. It would also make him understand that de default ones are his. Personnally I find it user-friendly
> 
> > I think it's good to disable the car and badge when only one is available
> 
> No, as you have to explain why it is disabled and the others not, so keep the same behavior for all.
But the behavior is not the same, When only one, we can't open the modal. Same visual will make think that it can always be opened
> 
> > Also I think it's good the keep sections labels/titles, the user instantaneously understands what are the settings, also when there is an error/placeholder message displayed
> > No, the user looks at the images not the text.
> 
> The icons (user, card, car) are self-explanatory, text only adds complexity to your eyes ;-).
Ok but when adding SoC and departure time, it would create a coherence as each setting section will have a title
> 
> > I've tried the rounded border in cars but it's weird ad the lines cut perpendicularly
> 
> I don't see what you mean (screenshot?)
Rounded is good actually

**Comment by LucasBrazi06** [comment]
> But I still think that the toggle for default settings is useful. Reset the settings to the one of the current user. It would also make him understand that de default ones are his. Personnally I find it user-friendly

The toggle button is useless: you already display the default settings and the user will change them if needed.
At worse there is only the need of a 'Reset to Default' button.

> Yes but the behavior is not the same. When only one item, the user can't open the modal so the same visual would precisely suggest the user that the modal can always be opened

Then he will have a list of 1 record and it's better than disabled + you don't know why.
Same behavior as in the Angular front end.

> Ok but when adding SoC and departure time, it would create a coherence as each setting section will have a title.
> Also, the payment method error is linked to the selected user, so the first section will contain two blocks

You can also have a label in the empty field.
The goal is to not add too much information in the UI.

> Rounded is good actually

Perfect :-)

**Comment by AlixH** [comment]
> > But I still think that the toggle for default settings is useful. Reset the settings to the one of the current user. It would also make him understand that de default ones are his. Personnally I find it user-friendly
> 
> The toggle button is useless: you already display the default settings and the user will change them if needed.
> At worse there is only the need of a 'Reset to Default' button.
> 
> > Yes but the behavior is not the same. When only one item, the user can't open the modal so the same visual would precisely suggest the user that the modal can always be opened
> 
> Then he will have a list of 1 record and it's better than disabled + you don't know why.
> Same behavior as in the Angular front end.

When an input is disabled it means that you don't have a choice for me, but ok 
(did this becaue Gerald did not like the fact that it can be opened with only one item ;) )
> 
> > Ok but when adding SoC and departure time, it would create a coherence as each setting section will have a title.
> > Also, the payment method error is linked to the selected user, so the first section will contain two blocks
> 
> You can also have a label in the empty field.

I don't understand, what empty field ? 
> The goal is to not add too much information in the UI.
> 
> > Rounded is good actually
> 
> Perfect :-)

**Comment by LucasBrazi06** [comment]
> When an input is disabled it means that you don't have a choice for me, but ok
> (did this becaue Gerald did not like the fact that it can be opened with only one item ;) )

Gerald is not sometime a good example 👯 

> I don't understand, what empty field ?

The departure date and the SoC can have a label in the input field.

**Comment by AlixH** [comment]
> > When an input is disabled it means that you don't have a choice for me, but ok
> > (did this becaue Gerald did not like the fact that it can be opened with only one item ;) )
> 
> Gerald is not sometime a good example 👯

So the user modal can also be opened for basic users ?
> 
> > I don't understand, what empty field ?
> 
> The departure date and the SoC can have a label in the input field.

**Comment by LucasBrazi06** [comment]
> So the user modal can also be opened for basic users ?

No

**Comment by AlixH** [comment]
> > So the user modal can also be opened for basic users ?
> 
> No

But still not disabled ?

**Comment by LucasBrazi06** [comment]
> > So the user modal can also be opened for basic users ?
> 
> No

It is hidden for Basic user not disabled.
Btw, remove sensitive data in your screenshots for the nth time ;-)

**Comment by LucasBrazi06** [comment]
Tiens je t'ai fait une golden rule rien que pour toi :-)

**Comment by AlixH** [comment]
> > > So the user modal can also be opened for basic users ?
> > 
> > 
> > No
> 
> It is hidden for Basic user not disabled.
> Btw, remove sensitive data in your screenshots for the nth time ;-)

My bad, I've deleted

**Pull request merged**
